# Randomly change some code & ensure lint equivalency is maintained
on:
  push:
    branches: [main]
  # TODO before merging: remove this. Only kept to demonstrate during review.
  pull_request:
    branches: [main]

name: ast-fuzz

jobs:
  repo-meta-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Ensure equivalent code generates equivalent lints
        run: |
          callr::rscript(".dev/ast_fuzz_test.R")
        shell: Rscript {0}
