# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.locale }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,  r: '4.0.0'}
          - {os: windows-latest,  r: '4.0.1'}
          - {os: windows-latest,  r: '4.0.2'}
          - {os: windows-latest,  r: '4.0.3'}
          - {os: windows-latest,  r: '4.0.4'}
          - {os: windows-latest,  r: '4.0.5'}
          - {os: windows-latest,  r: '4.1.0'}
          - {os: windows-latest,  r: '4.1.1'}
          - {os: windows-latest,  r: '4.1.2'}
          - {os: windows-latest,  r: '4.1.3'}
          - {os: windows-latest,  r: '4.2.0'}
          - {os: windows-latest,  r: '4.2.1'}
          - {os: windows-latest,  r: '4.2.2'}
          - {os: windows-latest,  r: '4.2.3'}
          - {os: windows-latest,  r: '4.3.0'}
          - {os: windows-latest,  r: '4.3.1'}
          - {os: windows-latest,  r: '4.3.2'}
          - {os: windows-latest,  r: '4.3.3'}
          - {os: windows-latest,  r: '4.4.0'}
          - {os: windows-latest,  r: '4.4.1'}
          - {os: windows-latest,  r: '4.4.2'}
          - {os: windows-latest,  r: 'devel'}
          - {os: macos-latest,  r: '4.0.0'}
          - {os: macos-latest,  r: '4.0.1'}
          - {os: macos-latest,  r: '4.0.2'}
          - {os: macos-latest,  r: '4.0.3'}
          - {os: macos-latest,  r: '4.0.4'}
          - {os: macos-latest,  r: '4.0.5'}
          - {os: macos-latest,  r: '4.1.0'}
          - {os: macos-latest,  r: '4.1.1'}
          - {os: macos-latest,  r: '4.1.2'}
          - {os: macos-latest,  r: '4.1.3'}
          - {os: macos-latest,  r: '4.2.0'}
          - {os: macos-latest,  r: '4.2.1'}
          - {os: macos-latest,  r: '4.2.2'}
          - {os: macos-latest,  r: '4.2.3'}
          - {os: macos-latest,  r: '4.3.0'}
          - {os: macos-latest,  r: '4.3.1'}
          - {os: macos-latest,  r: '4.3.2'}
          - {os: macos-latest,  r: '4.3.3'}
          - {os: macos-latest,  r: '4.4.0'}
          - {os: macos-latest,  r: '4.4.1'}
          - {os: macos-latest,  r: '4.4.2'}
          - {os: macos-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: '4.0.0'}
          - {os: ubuntu-latest,  r: '4.0.1'}
          - {os: ubuntu-latest,  r: '4.0.2'}
          - {os: ubuntu-latest,  r: '4.0.3'}
          - {os: ubuntu-latest,  r: '4.0.4'}
          - {os: ubuntu-latest,  r: '4.0.5'}
          - {os: ubuntu-latest,  r: '4.1.0'}
          - {os: ubuntu-latest,  r: '4.1.1'}
          - {os: ubuntu-latest,  r: '4.1.2'}
          - {os: ubuntu-latest,  r: '4.1.3'}
          - {os: ubuntu-latest,  r: '4.2.0'}
          - {os: ubuntu-latest,  r: '4.2.1'}
          - {os: ubuntu-latest,  r: '4.2.2'}
          - {os: ubuntu-latest,  r: '4.2.3'}
          - {os: ubuntu-latest,  r: '4.3.0'}
          - {os: ubuntu-latest,  r: '4.3.1'}
          - {os: ubuntu-latest,  r: '4.3.2'}
          - {os: ubuntu-latest,  r: '4.3.3'}
          - {os: ubuntu-latest,  r: '4.4.0'}
          - {os: ubuntu-latest,  r: '4.4.1'}
          - {os: ubuntu-latest,  r: '4.4.2'}
          - {os: ubuntu-latest,  r: 'devel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Set locale
        if: matrix.config.locale == 'en_US'
        run: |
          sudo locale-gen en_US
          echo "LC_ALL=en_US" >> $GITHUB_ENV

      - name: Set locale
        if: matrix.config.locale == 'zh_CN'
        run: |
          sudo locale-gen zh_CN
          echo "LC_ALL=zh_CN" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          install-quarto: false
          extra-packages: |
            any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"note"'
